// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ArgotReq.proto

package com.baihudie.api.proto;

public final class ArgotReqProto {
  private ArgotReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ArgotReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netty.ArgotReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 reqSeq = 1;</code>
     */
    int getReqSeq();

    /**
     * <code>int32 reqType = 2;</code>
     */
    int getReqType();

    /**
     * <code>string pseudonym = 3;</code>
     */
    String getPseudonym();
    /**
     * <code>string pseudonym = 3;</code>
     */
    com.google.protobuf.ByteString
        getPseudonymBytes();

    /**
     * <code>string body = 4;</code>
     */
    String getBody();
    /**
     * <code>string body = 4;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();
  }
  /**
   * Protobuf type {@code netty.ArgotReq}
   */
  public  static final class ArgotReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:netty.ArgotReq)
      ArgotReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ArgotReq.newBuilder() to construct.
    private ArgotReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ArgotReq() {
      pseudonym_ = "";
      body_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ArgotReq();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ArgotReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              reqSeq_ = input.readInt32();
              break;
            }
            case 16: {

              reqType_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              pseudonym_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ArgotReqProto.internal_static_netty_ArgotReq_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ArgotReqProto.internal_static_netty_ArgotReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ArgotReq.class, Builder.class);
    }

    public static final int REQSEQ_FIELD_NUMBER = 1;
    private int reqSeq_;
    /**
     * <code>int32 reqSeq = 1;</code>
     */
    public int getReqSeq() {
      return reqSeq_;
    }

    public static final int REQTYPE_FIELD_NUMBER = 2;
    private int reqType_;
    /**
     * <code>int32 reqType = 2;</code>
     */
    public int getReqType() {
      return reqType_;
    }

    public static final int PSEUDONYM_FIELD_NUMBER = 3;
    private volatile Object pseudonym_;
    /**
     * <code>string pseudonym = 3;</code>
     */
    public String getPseudonym() {
      Object ref = pseudonym_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pseudonym_ = s;
        return s;
      }
    }
    /**
     * <code>string pseudonym = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPseudonymBytes() {
      Object ref = pseudonym_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pseudonym_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 4;
    private volatile Object body_;
    /**
     * <code>string body = 4;</code>
     */
    public String getBody() {
      Object ref = body_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <code>string body = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      Object ref = body_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (reqSeq_ != 0) {
        output.writeInt32(1, reqSeq_);
      }
      if (reqType_ != 0) {
        output.writeInt32(2, reqType_);
      }
      if (!getPseudonymBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, pseudonym_);
      }
      if (!getBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, body_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (reqSeq_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, reqSeq_);
      }
      if (reqType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, reqType_);
      }
      if (!getPseudonymBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, pseudonym_);
      }
      if (!getBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ArgotReq)) {
        return super.equals(obj);
      }
      ArgotReq other = (ArgotReq) obj;

      if (getReqSeq()
          != other.getReqSeq()) return false;
      if (getReqType()
          != other.getReqType()) return false;
      if (!getPseudonym()
          .equals(other.getPseudonym())) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQSEQ_FIELD_NUMBER;
      hash = (53 * hash) + getReqSeq();
      hash = (37 * hash) + REQTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getReqType();
      hash = (37 * hash) + PSEUDONYM_FIELD_NUMBER;
      hash = (53 * hash) + getPseudonym().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ArgotReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ArgotReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ArgotReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ArgotReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ArgotReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ArgotReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ArgotReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ArgotReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ArgotReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ArgotReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ArgotReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ArgotReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ArgotReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.ArgotReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netty.ArgotReq)
        ArgotReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ArgotReqProto.internal_static_netty_ArgotReq_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ArgotReqProto.internal_static_netty_ArgotReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ArgotReq.class, Builder.class);
      }

      // Construct using com.baihudie.api.proto.ArgotReqProto.ArgotReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        reqSeq_ = 0;

        reqType_ = 0;

        pseudonym_ = "";

        body_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ArgotReqProto.internal_static_netty_ArgotReq_descriptor;
      }

      @Override
      public ArgotReq getDefaultInstanceForType() {
        return ArgotReq.getDefaultInstance();
      }

      @Override
      public ArgotReq build() {
        ArgotReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ArgotReq buildPartial() {
        ArgotReq result = new ArgotReq(this);
        result.reqSeq_ = reqSeq_;
        result.reqType_ = reqType_;
        result.pseudonym_ = pseudonym_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ArgotReq) {
          return mergeFrom((ArgotReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ArgotReq other) {
        if (other == ArgotReq.getDefaultInstance()) return this;
        if (other.getReqSeq() != 0) {
          setReqSeq(other.getReqSeq());
        }
        if (other.getReqType() != 0) {
          setReqType(other.getReqType());
        }
        if (!other.getPseudonym().isEmpty()) {
          pseudonym_ = other.pseudonym_;
          onChanged();
        }
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ArgotReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ArgotReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int reqSeq_ ;
      /**
       * <code>int32 reqSeq = 1;</code>
       */
      public int getReqSeq() {
        return reqSeq_;
      }
      /**
       * <code>int32 reqSeq = 1;</code>
       */
      public Builder setReqSeq(int value) {
        
        reqSeq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 reqSeq = 1;</code>
       */
      public Builder clearReqSeq() {
        
        reqSeq_ = 0;
        onChanged();
        return this;
      }

      private int reqType_ ;
      /**
       * <code>int32 reqType = 2;</code>
       */
      public int getReqType() {
        return reqType_;
      }
      /**
       * <code>int32 reqType = 2;</code>
       */
      public Builder setReqType(int value) {
        
        reqType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 reqType = 2;</code>
       */
      public Builder clearReqType() {
        
        reqType_ = 0;
        onChanged();
        return this;
      }

      private Object pseudonym_ = "";
      /**
       * <code>string pseudonym = 3;</code>
       */
      public String getPseudonym() {
        Object ref = pseudonym_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          pseudonym_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string pseudonym = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPseudonymBytes() {
        Object ref = pseudonym_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pseudonym_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pseudonym = 3;</code>
       */
      public Builder setPseudonym(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pseudonym_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pseudonym = 3;</code>
       */
      public Builder clearPseudonym() {
        
        pseudonym_ = getDefaultInstance().getPseudonym();
        onChanged();
        return this;
      }
      /**
       * <code>string pseudonym = 3;</code>
       */
      public Builder setPseudonymBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pseudonym_ = value;
        onChanged();
        return this;
      }

      private Object body_ = "";
      /**
       * <code>string body = 4;</code>
       */
      public String getBody() {
        Object ref = body_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string body = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string body = 4;</code>
       */
      public Builder setBody(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string body = 4;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>string body = 4;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        body_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:netty.ArgotReq)
    }

    // @@protoc_insertion_point(class_scope:netty.ArgotReq)
    private static final ArgotReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ArgotReq();
    }

    public static ArgotReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ArgotReq>
        PARSER = new com.google.protobuf.AbstractParser<ArgotReq>() {
      @Override
      public ArgotReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ArgotReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ArgotReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ArgotReq> getParserForType() {
      return PARSER;
    }

    @Override
    public ArgotReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_ArgotReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netty_ArgotReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016ArgotReq.proto\022\005netty\"L\n\010ArgotReq\022\016\n\006r" +
      "eqSeq\030\001 \001(\005\022\017\n\007reqType\030\002 \001(\005\022\021\n\tpseudony" +
      "m\030\003 \001(\t\022\014\n\004body\030\004 \001(\tB\'\n\026com.baihudie.ap" +
      "i.protoB\rArgotReqProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_netty_ArgotReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netty_ArgotReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netty_ArgotReq_descriptor,
        new String[] { "ReqSeq", "ReqType", "Pseudonym", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
