spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:argot.db
#    username:
#    password:

mybatis:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.baihudie.desktop.model












